-- Re-enable RLS on all tables
ALTER TABLE IF EXISTS user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workspaces ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS workspace_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS channel_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS direct_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS auth_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS founder_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS riddle_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS access_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS founder_code_count ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS encryption_keys ENABLE ROW LEVEL SECURITY; 